export const tickerToCompanyName: Record<string, string> = {
  NXLIW: "Nexalin Technology Inc.",
  IVVD: "Invivyd Inc.",
  ZOOZW: "ZOOZ Power Ltd.",
  SATS: "EchoStar Corporation",
  NUKKW: "Nukkleus Inc.",
  PXSAW: "Pixelworks Inc.",
  "BIT^": "Bitwise Industries",
  ALLR: "Allarity Therapeutics Inc.",
  CDIOW: "Cardio Diagnostics Holdings Inc.",
  GIBOW: "GigaBio Ltd.",
  VSME: "VS Media Holdings Ltd.",
  NRXPW: "NRX Pharmaceuticals Inc.",
  BNAIW: "Blockchain Acquisition Corp.",
  DHAIW: "DHC Acquisition Corp.",
  LEXXW: "Lexaria Bioscience Corp.",
  HUBCW: "Hub Cyber Security Ltd.",
  OABIW: "OmniAb Inc.",
  "BKKT+": "Bakkt Holdings Inc.",
  "RBOT+": "Vicarious Surgical Inc.",
  HKPD: "HKD Group Ltd.",

  EPIX: "EssilorLuxottica Inc.",
  YMAT: "Yumanity Therapeutics Inc.",
  BTBDW: "BT Brands Inc.",
  AUUDW: "Auddia Inc.",
  POLEW: "Polar Power Inc.",
  DOGZ: "Dogness Corporation",
  AERTW: "Aeries Technology Inc.",
  MYSEW: "MY SIZE Inc.",
  MNYWW: "MoneyLion Inc.",
  "HYAC+": "Haymaker Acquisition Corp.",
  KVACW: "Keen Vision Acquisition Corp.",
  EPWK: "Epoxy World Inc.",
  FEMY: "Femasys Inc.",
  SWAGW: "Software Acquisition Group Inc.",
  PTIXW: "Protagenic Therapeutics Inc.",
  "GWH+": "ESS Tech Inc.",
  EEIQ: "Elite Education Group International Ltd.",
  ODVWZ: "Odyssey Semiconductor Technologies Inc.",
  AIMDW: "AIMD Holdings Inc.",
  NIXXW: "NioCorp Developments Ltd.",

  IXHL: "Incannex Healthcare Ltd.",
  OPEN: "Opendoor Technologies Inc.",
  TNFA: "Tenaya Therapeutics Inc.",
  NVDA: "NVIDIA Corporation",
  WORX: "SCWorx Corp.",
  NIO: "NIO Inc.",
  TLRY: "Tilray Brands Inc.",
  SOFI: "SoFi Technologies Inc.",
  BENF: "Beneficient Company Group",
  PFSA: "Prime Focus Ltd.",
  RR: "Rolls-Royce Holdings plc",
  SOXS: "Direxion Daily Semiconductor Bear 3x Shares",
  TSLL: "Direxion Daily TSLA Bull 1.5x Shares",
  WBA: "Walgreens Boots Alliance Inc.",
  LCID: "Lucid Group Inc.",
  PLTR: "Palantir Technologies Inc.",
};
