export const sampleStockDetails = {
  "200DayMovingAverage": "7.84",
  "50DayMovingAverage": "2.817",
  "52WeekHigh": "15.8",
  "52WeekLow": "1.63",
  Address: "8901 E. MOUNTAIN VIEW RD., STE. 150, SCOTTSDALE, AZ, UNITED STATES",
  AnalystRatingBuy: "0",
  AnalystRatingHold: "0",
  AnalystRatingSell: "0",
  AnalystRatingStrongBuy: "0",
  AnalystRatingStrongSell: "0",
  AnalystTargetPrice: "6",
  AssetType: "Common Stock",
  Beta: "-0.648",
  BookValue: "-15.01",
  CIK: "1627282",
  Country: "USA",
  Currency: "USD",
  Description: "None",
  DilutedEPSTTM: "-18.13",
  DividendDate: "None",
  DividendPerShare: "None",
  DividendYield: "None",
  EBITDA: "-4827000",
  EPS: "-18.13",
  EVToEBITDA: "-17.36",
  EVToRevenue: "2.042",
  ExDividendDate: "None",
  Exchange: "NASDAQ",
  FiscalYearEnd: "December",
  ForwardPE: "7.13",
  GrossProfitTTM: "414000",
  Industry: "REAL ESTATE",
  LatestQuarter: "2025-06-30",
  MarketCapitalization: "4105600",
  Name: "CaliberCos Inc. Class A Common Stock",
  OfficialSite: "https://www.caliberco.com",
  OperatingMarginTTM: "-0.36",
  PEGRatio: "None",
  PERatio: "None",
  PercentInsiders: "28.037",
  PercentInstitutions: "0.796",
  PriceToBookRatio: "4.978",
  PriceToSalesRatioTTM: "0.127",
  ProfitMargin: "-0.648",
  QuarterlyEarningsGrowthYOY: "0",
  QuarterlyRevenueGrowthYOY: "-0.38",
  ReturnOnAssetsTTM: "-0.0438",
  ReturnOnEquityTTM: "-0.545",
  RevenuePerShareTTM: "27.79",
  RevenueTTM: "32323000",
  Sector: "REAL ESTATE & CONSTRUCTION",
  SharesFloat: "1404300",
  SharesOutstanding: "951390",
  Symbol: "CWD",
  TrailingPE: "-",
};

export const companyDescription = (company: string) => {
  return `We are a ${company}, dedicated to delivering innovative solutions that drive growth and efficiency. Our team is passionate about excellence, committed to client success, and focused on creating value through reliable services and forward-thinking strategies across industries.`;
};
